#!/usr/bin/env python3
"""
energy_pipeline_diagnostics_v1.py
=================================

This companion script provides diagnostic and visualization utilities for the
natural gas and oil forecasting pipeline.  It is designed to operate on
outputs produced by the ``energy_pipeline_forecast_v1.2.py`` script and to
recompute residual diagnostics when provided with the original data sources.

The script implements three key functions:

1. **Forecast Visualization**
   - Reads the ``forecasts_levels.csv`` file generated by the forecasting
     pipeline.
   - For natural gas (NG), computes a constant‐variance 95 % confidence
     interval based on the estimated variance of the ARIMAX mean model.
     This approximation yields fan charts around the forecast path.
   - For crude oil (OL), optionally refits a SARIMAX model on the provided
     data to obtain prediction intervals via Statsmodels.  If the original
     data are not provided, the script falls back to constant variance as
     well.
   - Generates separate matplotlib charts for NG and OL, saving them in
     ``<results_dir>/diagnostics``.

2. **Residual Diagnostics**
   - If the original series and exogenous regressors are supplied, the
     script reloads the data, reconstructs the ARIMAX models and the GARCH
     volatility model for NG, and computes standardized residuals.
   - Computes Ljung–Box and ARCH LM p‐values for both series to assess
     autocorrelation and remaining heteroskedasticity.
   - Performs the Jarque–Bera normality test on standardized residuals.
   - Plots ACF and PACF of the standardized residuals (one chart per
     series).  Each plot is saved in ``<results_dir>/diagnostics``.

3. **Performance Validation**
   - When provided with an external benchmark CSV (e.g. forecasts produced
     from an R workflow), computes RMSE and MAE for NG and OL level
     forecasts against the Python forecasts.
   - Optionally, the script can be extended to compute Diebold–Mariano
     statistics for comparative forecasting accuracy.

Usage example:

    python energy_pipeline_diagnostics_v1.py \
        --results_dir /path/to/Python\ Model\ Outputs \
        --ng_csv /path/to/NG_prompt_month_futures_price.csv \
        --ol_csv /path/to/Oil_prompt_month_futures_price.csv \
        --exog_csv /path/to/weather_lagged.csv \
        --agg_level none \
        --exog_cols HDD CDD HDD_l1 HDD_l2 HDD_l3 CDD_l1 CDD_l2 CDD_l3 HDD_3dma CDD_3dma \
        --ng_order 5 0 1 \
        --r_results_csv /path/to/R_forecasts.csv

The script is intended to be modular; if no original data are provided, it
will still produce forecast plots using constant variance approximations.

"""

from __future__ import annotations

import argparse
import os
import json
from typing import List, Optional, Tuple, Dict

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import warnings

from statsmodels.tsa.statespace.sarimax import SARIMAX
from statsmodels.stats.diagnostic import acorr_ljungbox, het_arch
from statsmodels.stats.stattools import jarque_bera

# Attempt to import arch for GARCH diagnostics
try:
    from arch.univariate import arch_model
    HAVE_ARCH = True
except Exception:
    HAVE_ARCH = False
import argparse
import os
import pandas as pd
import numpy as np

# ==============================
# Parse command-line arguments
# ==============================
parser = argparse.ArgumentParser(description="Energy Forecast Diagnostics Script")

parser.add_argument("--results_dir", type=str, required=True,
                    help="Directory containing forecasts_levels.csv and model outputs")
parser.add_argument("--r_results_csv", type=str, default=None,
                    help="Optional: Combined R benchmark CSV")
parser.add_argument("--r_ng_csv", type=str, default=None,
                    help="Optional: R NG forecast CSV (e.g., ng_forecasts_scenario.csv)")
parser.add_argument("--r_ol_csv", type=str, default=None,
                    help="Optional: R Oil forecast CSV (e.g., oil_forecasts_scenario.csv)")

# Parse args from the command line
parsed_args = parser.parse_args()

def _load_r_fc(path: str, commodity: str) -> pd.DataFrame:
    """
    Load an R forecast CSV with flexible column names.
    Required info: date, horizon, level (forecasted level price).
    Optional: scenario column.
    """
    if path is None:
        return pd.DataFrame()
    df = pd.read_csv(path)
    cols = {c.lower(): c for c in df.columns}

    # Try to find columns
    date_col = cols.get("date") or cols.get("ds") or cols.get("time") or list(df.columns)[0]
    hor_col  = cols.get("horizon") or cols.get("h") or "horizon"
    lvl_col  = cols.get("level") or cols.get("forecast") or cols.get("yhat") or "level"
    scen_col = cols.get("scenario")  # optional

    # Normalize
    out = pd.DataFrame({
        "date": pd.to_datetime(df[date_col]),
        "horizon": df[hor_col].astype(int) if hor_col in df else np.arange(1, len(df)+1),
        "level": pd.to_numeric(df[lvl_col], errors="coerce")
    })
    out["commodity"] = commodity
    if scen_col:
        out["scenario"] = df[scen_col].astype(str)
    else:
        out["scenario"] = "R_default"
    return out.dropna(subset=["date", "horizon", "level"])


##########################
# Data loading utilities #
##########################

def read_table_any(path: str) -> pd.DataFrame:
    """Read a CSV/TSV file, sniffing delimiters automatically."""
    return pd.read_csv(path, sep=None, engine="python")


def _infer_columns(df: pd.DataFrame) -> Tuple[str, str]:
    """Infer date and price columns from a price CSV."""
    date_candidates = ["date", "Date", "DATE", "timestamp", "Timestamp"]
    price_candidates = [
        "PRICE_NG", "PRICE_OL", "price", "Price",
        "settle", "Settle", "PX_LAST"
    ]
    dcol = next((c for c in date_candidates if c in df.columns), None)
    if dcol is None:
        # fallback: try any column convertible to datetime
        for c in df.columns:
            try:
                pd.to_datetime(df[c])
                dcol = c
                break
            except Exception:
                continue
    if dcol is None:
        raise ValueError("Could not infer a date column in price CSV.")
    pcol = next((c for c in price_candidates if c in df.columns), None)
    if pcol is None:
        # fallback: first numeric column not date
        for c in df.columns:
            if c == dcol:
                continue
            if pd.api.types.is_numeric_dtype(df[c]):
                pcol = c
                break
    if pcol is None:
        raise ValueError("Could not infer a price column in price CSV.")
    return dcol, pcol

# ---- Load R forecasts if provided ----
r_ng = _load_r_fc(parsed_args.r_ng_csv, "NG") if parsed_args.r_ng_csv else pd.DataFrame()
r_ol = _load_r_fc(parsed_args.r_ol_csv, "OL") if parsed_args.r_ol_csv else pd.DataFrame()
have_r = (not r_ng.empty) or (not r_ol.empty)

if have_r:
    r_all = pd.concat([r_ng, r_ol], ignore_index=True)

    # Ensure we have the Python forecasts loaded as 'forecasts'
    # (If you loaded them earlier with a different name, keep that.)
    if "forecasts" not in locals():
        fpath = os.path.join(parsed_args.results_dir, "forecasts_levels.csv")
        forecasts = pd.read_csv(fpath, parse_dates=["date"])

    # Build Python forecasts in comparable long format
    py_fc = forecasts.copy()
    required = {"date", "horizon", "NG_level_forecast", "OL_level_forecast"}
    if not required.issubset(set(py_fc.columns)):
        missing = sorted(list(required - set(py_fc.columns)))
        raise ValueError(f"forecasts_levels.csv missing expected columns: {missing}")

    # Normalize dtypes
    py_fc["date"] = pd.to_datetime(py_fc["date"])
    r_all["date"]  = pd.to_datetime(r_all["date"])

    py_ng = py_fc[["date", "horizon", "NG_level_forecast"]].rename(
        columns={"NG_level_forecast": "level"}
    )
    py_ng["commodity"] = "NG"
    py_ng["scenario"]  = "PY"

    py_ol = py_fc[["date", "horizon", "OL_level_forecast"]].rename(
        columns={"OL_level_forecast": "level"}
    )
    py_ol["commodity"] = "OL"
    py_ol["scenario"]  = "PY"

    py_all = pd.concat([py_ng, py_ol], ignore_index=True)

    # Align by commodity + date + horizon (if R has multiple scenarios, this keeps them separate)
    join_cols = ["commodity", "date", "horizon"]
    comp = r_all.merge(py_all, on=join_cols, how="inner", suffixes=("_R", "_PY"))
        # Normalize a single 'scenario' column for grouping
    if "scenario_R" in comp.columns:
        comp["scenario"] = comp["scenario_R"].astype(str)
    elif "scenario" in comp.columns:
        comp["scenario"] = comp["scenario"].astype(str)
    else:
        comp["scenario"] = "R_default"

    # Metrics per commodity & R scenario
    def _metrics(g):
        diff = g["level_PY"].astype(float) - g["level_R"].astype(float)
        rmse = float(np.sqrt(np.mean(diff**2)))
        mae  = float(np.mean(np.abs(diff)))
        return pd.Series({"RMSE_PY_vs_R": rmse, "MAE_PY_vs_R": mae, "n": int(len(g))})

    summary = (comp
               .groupby(["commodity", "scenario"], dropna=False)
               .apply(_metrics)
               .reset_index())

    print("\n=== Python vs R Forecast Comparison (levels) ===")
    print(summary.to_string(index=False))

    out_csv = os.path.join(parsed_args.results_dir, "python_vs_r_comparison.csv")
    summary.to_csv(out_csv, index=False)
    print(f"\nSaved: {out_csv}")
else:
    print("\nNo R forecast CSVs provided — skipping Python vs R comparison.")



def load_price_csv(path: str, label: str) -> pd.DataFrame:
    """Load a price CSV and return a DataFrame with columns ['date', label]."""
    df = read_table_any(path)
    dcol, pcol = _infer_columns(df)
    df = df[[dcol, pcol]].copy()
    df.columns = ["date", label]
    df["date"] = pd.to_datetime(df["date"], errors="coerce").dt.tz_localize(None)
    df = df.dropna(subset=["date"]).sort_values("date").reset_index(drop=True)
    df = df.groupby("date", as_index=False).last()
    return df


def load_exog_csv(path: Optional[str]) -> Optional[pd.DataFrame]:
    """Load exogenous regressors with a date column. Returns None if path is None."""
    if not path:
        return None
    ex = read_table_any(path)
    date_candidates = ["date", "Date", "DATE", "timestamp", "Timestamp"]
    dcol = next((c for c in date_candidates if c in ex.columns), None)
    if dcol is None:
        raise ValueError("Exogenous CSV must contain a date column.")
    ex["date"] = pd.to_datetime(ex[dcol], errors="coerce").dt.tz_localize(None)
    ex = ex.dropna(subset=["date"]).sort_values("date").reset_index(drop=True)
    ex = ex.drop(columns=[dcol], errors="ignore")
    return ex


def make_lags(ex_df: pd.DataFrame, cols: List[str], max_lag: int = 2) -> pd.DataFrame:
    """Create lagged versions of numeric columns up to max_lag."""
    out = ex_df.copy()
    for c in cols:
        for L in range(1, max_lag + 1):
            out[f"{c}_l{L}"] = out[c].shift(L)
    return out


def align_calendar(ng: pd.DataFrame, ol: pd.DataFrame, exog: Optional[pd.DataFrame]) -> pd.DataFrame:
    """Merge NG, OL, and exog on the date column and forward-fill exog features."""
    df = pd.merge(ng, ol, on="date", how="outer")
    if exog is not None:
        df = pd.merge(df, exog, on="date", how="left")
    df = df.sort_values("date").reset_index(drop=True)
    if exog is not None:
        noncore = [c for c in df.columns if c not in ["date", "NG", "OL"]]
        df[noncore] = df[noncore].ffill()
    return df


def add_transforms(df: pd.DataFrame) -> pd.DataFrame:
    """Add log and first-difference log transformations for NG and OL."""
    df = df.copy()
    df["log_NG"] = np.log(df["NG"])
    df["log_OL"] = np.log(df["OL"])
    df["dlog_NG"] = df["log_NG"].diff()
    df["dlog_OL"] = df["log_OL"].diff()
    return df


#########################################
# Forecast visualization helper function #
#########################################

def compute_ng_ci_from_sigma2(
    forecasts: pd.DataFrame,
    sigma2: float,
    last_price: float
) -> pd.DataFrame:
    """
    Compute 95% confidence intervals for NG level forecasts assuming
    constant variance sigma2 for log returns.  This uses the property
    that the variance of the sum of independent log returns is the sum
    of their variances.  The resulting confidence interval is
    exp(cumulative mean ± 1.96 * sqrt(h * sigma2)) times the last price.

    Parameters
    ----------
    forecasts : DataFrame
        Must contain columns ['horizon', 'NG_level_forecast'] for a
        single horizon group (H) only.  The DataFrame should be in
        increasing horizon order.
    sigma2 : float
        Estimated variance of one‐step log returns from the mean model.
    last_price : float
        Last observed NG price, used to convert log returns to levels.

    Returns
    -------
    DataFrame with additional columns 'NG_lower' and 'NG_upper'.
    """
    # Compute cumulative log return from level path
    # log(path_t) = log(last_price) + cumulative log returns
    # We recover cumulative log returns as log(f_t / last_price)
    log_pred = np.log(forecasts["NG_level_forecast"] / last_price)
    horizons = forecasts["horizon"].values
    # Cumulative variance for horizon h: h * sigma2
    cum_var = horizons * sigma2
    z = 1.96
    # Lower and upper log forecasts
    log_lower = log_pred - z * np.sqrt(cum_var)
    log_upper = log_pred + z * np.sqrt(cum_var)
    forecasts = forecasts.copy()
    forecasts["NG_lower"] = last_price * np.exp(log_lower)
    forecasts["NG_upper"] = last_price * np.exp(log_upper)
    return forecasts


def visualize_forecasts(
    forecasts_file: str,
    params_ng_file: str,
    params_ol_file: str,
    results_dir: str,
    original_data: Optional[Dict[str, str]] = None,
    exog_cols: Optional[List[str]] = None,
    ng_order: Tuple[int, int, int] = (5, 0, 1),
    horizons: Optional[List[int]] = None
) -> None:
    """
    Generate and save forecast plots with confidence intervals.

    Parameters
    ----------
    forecasts_file : str
        Path to the forecasts CSV generated by the forecasting pipeline.
    params_ng_file : str
        Path to params_ng.json for NG model parameters.
    params_ol_file : str
        Path to params_ol.json for OL model parameters.
    results_dir : str
        Directory where plot images will be saved (subdir 'diagnostics').
    original_data : dict, optional
        If provided, must contain 'ng_csv', 'ol_csv', and optionally
        'exog_csv' and other keys.  When provided, the script will
        re-fit the SARIMAX mean models to compute forecast intervals
        using Statsmodels.  If None, constant variance intervals are
        used for both NG and OL.
    exog_cols : list[str], optional
        Names of exogenous columns to include when re-fitting models.
    ng_order : tuple[int, int, int]
        ARIMA order for NG mean when re-fitting.
    horizons : list[int], optional
        List of forecast horizons.  If None, unique horizons from
        forecasts_file will be used.
    """
    os.makedirs(os.path.join(results_dir, "diagnostics"), exist_ok=True)
    fc_all = pd.read_csv(forecasts_file)
    # Determine horizon groups
    if horizons is None:
        horizons = sorted(fc_all["H"].unique())
    # Load NG variance and last price
    with open(params_ng_file, "r") as f:
        params_ng = json.load(f)
    sigma2_ng = params_ng["mean"].get("sigma2")
    if sigma2_ng is None:
        sigma2_ng = params_ng["mean"].get("sigma2", 0.0)
    # Last observed price
    last_ng = float(fc_all.loc[fc_all["horizon"] == 1, "NG_level_forecast"].iloc[0])
    last_ol = float(fc_all.loc[fc_all["horizon"] == 1, "OL_level_forecast"].iloc[0])
    # Prepare plots for each horizon group separately
    for H in horizons:
        df_h = fc_all[fc_all["H"] == H].copy().sort_values("horizon")
        # Compute NG CI (constant variance assumption)
        df_ci = compute_ng_ci_from_sigma2(df_h, sigma2_ng, last_ng)
        # Plot NG path with CI
        plt.figure()
        plt.plot(df_h["date"], df_h["NG_level_forecast"], label="NG forecast")
        plt.fill_between(df_h["date"], df_ci["NG_lower"], df_ci["NG_upper"], alpha=0.2, label="95% CI")
        plt.title(f"Natural Gas Level Forecast (H={H})")
        plt.xlabel("Date")
        plt.ylabel("NG price")
        plt.legend()
        plt.xticks(rotation=45)
        plt.tight_layout()
        plt.savefig(os.path.join(results_dir, "diagnostics", f"NG_forecast_H{H}.png"))
        plt.close()
        # Oil CI
        # Try to re-fit SARIMAX for OL if original data provided
        ol_ci_lower = None
        ol_ci_upper = None
        if original_data is not None and all(k in original_data for k in ["ng_csv", "ol_csv"]):
            # Load dataset and refit SARIMAX for OL mean
            ng_df = load_price_csv(original_data["ng_csv"], "NG")
            ol_df = load_price_csv(original_data["ol_csv"], "OL")
            exog_df = load_exog_csv(original_data.get("exog_csv"))
            # If exogenous lags were provided, make lags
            if exog_df is not None:
                # Determine numeric columns in exog_df
                ex_num_cols = [c for c in exog_df.columns if c != "date" and pd.api.types.is_numeric_dtype(exog_df[c])]
                if ex_num_cols:
                    max_lag = 0
                    # derive max lag from names provided in exog_cols, e.g. HDD_l3 -> 3
                    if exog_cols:
                        for c in exog_cols:
                            if "_l" in c:
                                try:
                                    lag_val = int(c.split("_l")[-1])
                                    max_lag = max(max_lag, lag_val)
                                except Exception:
                                    pass
                    if max_lag > 0:
                        exog_df = make_lags(exog_df, ex_num_cols, max_lag=max_lag)
            df = align_calendar(ng_df, ol_df, exog_df)
            df = add_transforms(df)
            # Build exog matrix for OL
            if exog_cols:
                X_ol_full = df.set_index("date")[exog_cols].reindex(df.set_index("date").index)
            else:
                X_ol_full = None
            # Collapse returns for fitting
            y_ol_full = df.set_index("date")["dlog_OL"].dropna()
            X_ol_fit = None
            if X_ol_full is not None:
                X_ol_fit = X_ol_full.loc[y_ol_full.index]
            # Fit SARIMAX for Oil mean
            # Convert to arrays to avoid date-index warnings
            y_ol_arr = y_ol_full.to_numpy()
            X_ol_arr = None if X_ol_fit is None else X_ol_fit.to_numpy()
            try:
                res_ol = SARIMAX(y_ol_arr, order=(0, 0, 4), trend="n", exog=X_ol_arr,
                                 enforce_stationarity=False, enforce_invertibility=False
                                 ).fit(maxiter=4000, disp=False, method="powell")
            except Exception:
                res_ol = SARIMAX(y_ol_arr, order=(0, 0, 4), trend="n", exog=X_ol_arr,
                                 enforce_stationarity=False, enforce_invertibility=False
                                 ).fit(maxiter=4000, disp=False, method="lbfgs")
            # Build future exog (carry forward last values)
            if X_ol_arr is not None:
                last_row = X_ol_arr[-1]
                exog_ol_oos_arr = np.tile(last_row[None, :], (H, 1))
            else:
                exog_ol_oos_arr = None
            start_ol = len(y_ol_arr)
            end_ol = start_ol + H - 1
            ol_pred = res_ol.get_prediction(start=start_ol, end=end_ol, exog=exog_ol_oos_arr)
            pred_mean = ol_pred.predicted_mean
            conf_int = ol_pred.conf_int(alpha=0.05)
            # conf_int is shape (H, 2)
            # Build level paths
            log_pred = np.cumsum(np.asarray(pred_mean))
            log_lower = np.cumsum(conf_int[:, 0])
            log_upper = np.cumsum(conf_int[:, 1])
            ol_ci_lower = last_ol * np.exp(log_lower)
            ol_ci_upper = last_ol * np.exp(log_upper)
        # Plot OL path
        plt.figure()
        plt.plot(df_h["date"], df_h["OL_level_forecast"], label="OL forecast")
        if ol_ci_lower is not None and ol_ci_upper is not None:
            plt.fill_between(df_h["date"], ol_ci_lower, ol_ci_upper, alpha=0.2, label="95% CI")
        else:
            # constant variance using sigma2 from params_ol
            with open(params_ol_file, "r") as f:
                params_ol = json.load(f)
            sigma2_ol = params_ol.get("arimax", {}).get("sigma2")
            if sigma2_ol is None:
                sigma2_ol = params_ol.get("arimax", {}).get("sigma2", 0.0)
            # compute CI similar to NG constant variance
            log_pred = np.log(df_h["OL_level_forecast"] / last_ol)
            horizons_vec = df_h["horizon"].values
            cum_var = horizons_vec * sigma2_ol
            z = 1.96
            log_lower = log_pred - z * np.sqrt(cum_var)
            log_upper = log_pred + z * np.sqrt(cum_var)
            lower_path = last_ol * np.exp(log_lower)
            upper_path = last_ol * np.exp(log_upper)
            plt.fill_between(df_h["date"], lower_path, upper_path, alpha=0.2, label="95% CI")
        plt.title(f"Crude Oil Level Forecast (H={H})")
        plt.xlabel("Date")
        plt.ylabel("Oil price")
        plt.legend()
        plt.xticks(rotation=45)
        plt.tight_layout()
        plt.savefig(os.path.join(results_dir, "diagnostics", f"OL_forecast_H{H}.png"))
        plt.close()


##########################################
# Residual diagnostics helper functions   #
##########################################

def compute_residual_diagnostics(
    df: pd.DataFrame,
    exog_cols: Optional[List[str]],
    ng_order: Tuple[int, int, int],
    horizons: List[int],
    results_dir: str
) -> Dict[str, Dict[str, float]]:
    """
    Compute and save residual diagnostics for NG and OL.

    Fits ARIMAX and GARCH models using the supplied DataFrame
    (must include columns date, dlog_NG, dlog_OL, plus exogenous variables).

    Returns a dictionary with Ljung–Box and ARCH LM p-values and Jarque–Bera
    statistics for each series.
    """
    diagnostics = {}
    # Fit NG mean model (ARIMAX) and volatility model if possible
    # Build exog matrix for NG
    y_ng = df.set_index("date")["dlog_NG"].dropna()
    X_ng = None
    if exog_cols:
        X_ng_full = df.set_index("date")[exog_cols]
        X_ng = X_ng_full.loc[y_ng.index]
    # Fit SARIMAX mean
    p, d, q = ng_order
    y_ng_arr = y_ng.to_numpy()
    X_ng_arr = None if X_ng is None else X_ng.to_numpy()
    try:
        res_ng = SARIMAX(
            y_ng_arr, order=(p, d, q), trend="n",
            exog=X_ng_arr, enforce_stationarity=False, enforce_invertibility=False
        ).fit(maxiter=4000, disp=False, method="powell")
    except Exception:
        res_ng = SARIMAX(
            y_ng_arr, order=(p, d, q), trend="n",
            exog=X_ng_arr, enforce_stationarity=False, enforce_invertibility=False
        ).fit(maxiter=4000, disp=False, method="lbfgs")
    resid_ng = pd.Series(res_ng.resid, index=y_ng.index).dropna()
    # Fit GARCH on residuals (if possible)
    if HAVE_ARCH:
        try:
            # Student t distribution by default
            # Scale residuals by 100 to improve numerical stability
            scale = 100.0
            am = arch_model(resid_ng.values * scale, p=1, o=0, q=1, mean="zero", vol="Garch", dist="t")
            gfit = am.fit(update_freq=0, disp="off", show_warning=False, options={"maxiter": 4000})
            # Standardised residuals on original scale
            cond_vol = gfit.conditional_volatility / scale
            std_resid = (resid_ng / cond_vol)
        except Exception:
            std_resid = resid_ng / np.std(resid_ng.dropna())
    else:
        std_resid = resid_ng / np.std(resid_ng.dropna())
    # Diagnostics for NG
    lb_ng = acorr_ljungbox(std_resid.dropna(), lags=[20], return_df=True)
    lb_p_ng = float(lb_ng["lb_pvalue"].iloc[0])
    try:
        lm_stat_ng, lm_p_ng, _, _ = het_arch(std_resid.dropna(), nlags=20)
        arch_p_ng = float(lm_p_ng)
    except Exception:
        arch_p_ng = float("nan")
    jb_stat_ng, jb_p_ng, _, _ = jarque_bera(std_resid.dropna())
    # Plot ACF/PACF for NG residuals
    from statsmodels.graphics.tsaplots import plot_acf, plot_pacf
    plt.figure()
    plot_acf(std_resid.dropna(), lags=20)
    plt.title("ACF of NG standardized residuals")
    plt.tight_layout()
    plt.savefig(os.path.join(results_dir, "diagnostics", "NG_resid_acf.png"))
    plt.close()
    plt.figure()
    plot_pacf(std_resid.dropna(), lags=20, method="ywm")
    plt.title("PACF of NG standardized residuals")
    plt.tight_layout()
    plt.savefig(os.path.join(results_dir, "diagnostics", "NG_resid_pacf.png"))
    plt.close()
    diagnostics["NG"] = {
        "ljungbox_p": lb_p_ng,
        "arch_lm_p": arch_p_ng,
        "jarque_bera_p": float(jb_p_ng)
    }
    # Fit OL mean model (ARIMAX(0,0,4))
    y_ol = df.set_index("date")["dlog_OL"].dropna()
    X_ol = None
    if exog_cols:
        X_ol_full = df.set_index("date")[exog_cols]
        X_ol = X_ol_full.loc[y_ol.index]
    y_ol_arr = y_ol.to_numpy()
    X_ol_arr = None if X_ol is None else X_ol.to_numpy()
    try:
        res_ol = SARIMAX(
            y_ol_arr, order=(0, 0, 4), trend="n",
            exog=X_ol_arr, enforce_stationarity=False, enforce_invertibility=False
        ).fit(maxiter=4000, disp=False, method="powell")
    except Exception:
        res_ol = SARIMAX(
            y_ol_arr, order=(0, 0, 4), trend="n",
            exog=X_ol_arr, enforce_stationarity=False, enforce_invertibility=False
        ).fit(maxiter=4000, disp=False, method="lbfgs")
    resid_ol = pd.Series(res_ol.resid, index=y_ol.index).dropna()
    std_resid_ol = resid_ol / np.std(resid_ol.dropna())
    lb_ol = acorr_ljungbox(std_resid_ol.dropna(), lags=[20], return_df=True)
    lb_p_ol = float(lb_ol["lb_pvalue"].iloc[0])
    try:
        lm_stat_ol, lm_p_ol, _, _ = het_arch(std_resid_ol.dropna(), nlags=20)
        arch_p_ol = float(lm_p_ol)
    except Exception:
        arch_p_ol = float("nan")
    jb_stat_ol, jb_p_ol, _, _ = jarque_bera(std_resid_ol.dropna())
    # Plot ACF/PACF for OL residuals
    plt.figure()
    plot_acf(std_resid_ol.dropna(), lags=20)
    plt.title("ACF of OL standardized residuals")
    plt.tight_layout()
    plt.savefig(os.path.join(results_dir, "diagnostics", "OL_resid_acf.png"))
    plt.close()
    plt.figure()
    plot_pacf(std_resid_ol.dropna(), lags=20, method="ywm")
    plt.title("PACF of OL standardized residuals")
    plt.tight_layout()
    plt.savefig(os.path.join(results_dir, "diagnostics", "OL_resid_pacf.png"))
    plt.close()
    diagnostics["OL"] = {
        "ljungbox_p": lb_p_ol,
        "arch_lm_p": arch_p_ol,
        "jarque_bera_p": float(jb_p_ol)
    }
    # Save diagnostics summary JSON
    with open(os.path.join(results_dir, "diagnostics", "residual_diagnostics.json"), "w") as f:
        json.dump(diagnostics, f, indent=2)
    return diagnostics


###########################################
# Performance validation helper functions  #
###########################################

def compute_performance_metrics(
    python_forecasts: pd.DataFrame,
    r_forecasts: pd.DataFrame
) -> Dict[str, Dict[str, float]]:
    """
    Compute RMSE and MAE between Python and R forecasts for NG and OL level
    forecasts.  Both DataFrames must have columns ['date','horizon',
    'NG_level_forecast','OL_level_forecast'] and cover the same dates and
    horizons.  The function groups by horizon and computes metrics for each
    series separately.
    Returns a dictionary keyed by horizon and series.
    """
    metrics = {}
    # Merge on date and horizon
    merged = pd.merge(
        python_forecasts,
        r_forecasts,
        on=["date", "horizon"],
        suffixes=("_py", "_r"),
        how="inner"
    )
    if merged.empty:
        raise ValueError("No overlapping forecasts between Python and R results.")
    for H in sorted(merged["horizon"].unique()):
        df_h = merged[merged["horizon"] == H]
        err_ng = df_h["NG_level_forecast_py"] - df_h["NG_level_forecast_r"]
        err_ol = df_h["OL_level_forecast_py"] - df_h["OL_level_forecast_r"]
        rmse_ng = float(np.sqrt(np.mean(err_ng ** 2)))
        rmse_ol = float(np.sqrt(np.mean(err_ol ** 2)))
        mae_ng = float(np.mean(np.abs(err_ng)))
        mae_ol = float(np.mean(np.abs(err_ol)))
        metrics[f"H={H}"] = {
            "NG_RMSE": rmse_ng,
            "NG_MAE": mae_ng,
            "OL_RMSE": rmse_ol,
            "OL_MAE": mae_ol,
        }
    return metrics


###########################################
# Main CLI interface                      #
###########################################

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Diagnostics and visualization for NG/OL forecasting pipeline."
    )
    parser.add_argument("--results_dir", type=str, required=True,
                        help="Directory containing pipeline outputs (forecasts_levels.csv, params_*.json).")
    parser.add_argument("--ng_csv", type=str, default=None,
                        help="Path to NG price CSV for refitting models (optional).")
    parser.add_argument("--ol_csv", type=str, default=None,
                        help="Path to OL price CSV for refitting models (optional).")
    parser.add_argument("--exog_csv", type=str, default=None,
                        help="Path to exogenous regressors CSV for refitting models (optional).")
    parser.add_argument("--agg_level", type=str, default="none",
                        choices=["none", "national", "division"],
                        help="Aggregation level for exogenous data (unused here).")
    parser.add_argument("--exog_cols", type=str, nargs="*", default=None,
                        help="Names of exogenous columns to include after lagging.")
    parser.add_argument("--ng_order", type=int, nargs=3, default=[5, 0, 1],
                        help="ARIMA order for NG mean model.")
    parser.add_argument("--horizons", type=int, nargs="*", default=None,
                        help="List of forecast horizons to process.  If omitted, uses unique horizons from forecasts file.")
    parser.add_argument("--r_results_csv", type=str, default=None,
                        help="Path to R-generated forecast CSV for performance validation (optional).")
    parser.add_argument("--r_ng_csv", type=str, default=None,
                    help="Path to R NG forecast CSV (e.g., ng_forecasts_scenario.csv)")
    parser.add_argument("--r_ol_csv", type=str, default=None,
                    help="Path to R Oil forecast CSV (e.g., oil_forecasts_scenario.csv)")

    args = parser.parse_args()
    # Locate files in results_dir
    forecasts_file = os.path.join(args.results_dir, "forecasts_levels.csv")
    params_ng_file = os.path.join(args.results_dir, "params_ng.json")
    params_ol_file = os.path.join(args.results_dir, "params_ol.json")
    if not os.path.isfile(forecasts_file):
        raise FileNotFoundError(f"Forecasts file not found: {forecasts_file}")
    if not os.path.isfile(params_ng_file):
        raise FileNotFoundError(f"params_ng.json not found in {args.results_dir}")
    if not os.path.isfile(params_ol_file):
        raise FileNotFoundError(f"params_ol.json not found in {args.results_dir}")
    # Step 1: Forecast visualization
    original_data = None
    if args.ng_csv and args.ol_csv:
        original_data = {
            "ng_csv": args.ng_csv,
            "ol_csv": args.ol_csv,
            "exog_csv": args.exog_csv,
        }
    visualize_forecasts(
        forecasts_file,
        params_ng_file,
        params_ol_file,
        args.results_dir,
        original_data=original_data,
        exog_cols=args.exog_cols,
        ng_order=tuple(args.ng_order),
        horizons=args.horizons
    )
    # Step 2: Residual diagnostics (if original data provided)
    if original_data is not None:
        # Load and prepare full dataframe for diagnostics
        ng_df = load_price_csv(args.ng_csv, "NG")
        ol_df = load_price_csv(args.ol_csv, "OL")
        exog_df = load_exog_csv(args.exog_csv)
        # Determine maximum lag for exogenous columns
        if exog_df is not None and args.exog_cols:
            ex_num_cols = [c for c in exog_df.columns if c != "date" and pd.api.types.is_numeric_dtype(exog_df[c])]
            max_lag = 0
            for c in args.exog_cols:
                if "_l" in c:
                    try:
                        lag_val = int(c.split("_l")[-1])
                        max_lag = max(max_lag, lag_val)
                    except Exception:
                        pass
            if max_lag > 0 and ex_num_cols:
                exog_df = make_lags(exog_df, ex_num_cols, max_lag=max_lag)
        df = align_calendar(ng_df, ol_df, exog_df)
        df = add_transforms(df)
        diagnostics = compute_residual_diagnostics(
            df,
            args.exog_cols,
            tuple(args.ng_order),
            args.horizons or sorted(pd.read_csv(forecasts_file)["H"].unique()),
            args.results_dir
        )
        print("Residual diagnostics:")
        for series, stats in diagnostics.items():
            print(series, stats)
    # Step 3: Performance validation (optional)
    if args.r_results_csv:
        py_fc = pd.read_csv(forecasts_file)
        r_fc = pd.read_csv(args.r_results_csv)
        metrics = compute_performance_metrics(py_fc, r_fc)
        print("Performance validation (Python vs R):")
        for h, m in metrics.items():
            print(h, m)
        # Save metrics JSON
        with open(os.path.join(args.results_dir, "diagnostics", "performance_metrics.json"), "w") as f:
            json.dump(metrics, f, indent=2)


if __name__ == "__main__":
    main()